CREATE TABLE course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE pricing_zone (
    code VARCHAR(50) PRIMARY KEY,
    currency VARCHAR(10) NOT NULL,
    symbol VARCHAR(5) NOT NULL
);

CREATE TABLE country_pricing_zone (
    country_code VARCHAR(10) PRIMARY KEY,
    pricing_zone_code VARCHAR(50) NOT NULL
);

CREATE TABLE course_price (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    pricing_zone_code VARCHAR(50) NOT NULL,
    amount INT NOT NULL
);

